version: '3.1'

services:
  web:
    build: ./e_auctions
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./e_auctions/:/usr/src/e_auctions/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
